' Copiar e colar no PlantUML: https://www.planttext.com/
' Referente ao Diagrama de Classes do Projeto (Módulos de Pessoas e Acesso)

@startuml

enum Sexo {
  + FEMININO
  + MASCULINO
  + PREFIRO_NAO_INFORMAR
  + OUTRO
}

enum Escolaridade {
  + FUNDAMENTAL_INCOMPLETO
  + FUNDAMENTAL_COMPLETO
  + MEDIO_INCOMPLETO
  + MEDIO_COMPLETO
  + SUPERIOR_INCOMPLETO
  + SUPERIOR_COMPLETO
}

enum RendaFamiliar {
  + MENOS_DE_MIL
  + ENTRE_MIL_E_DOIS_MIL
  + ENTRE_DOIS_MIL_E_TRES_MIL
  + MAIOR_QUE_TRES_MIL
}

enum Uf {
  + AC
  + AL
  + AM
  + AP
  + BA
  + CE
  + DF
  + ES
  + GO
  + MA
  + MG
  + MS
  + MT
  + PA
  + PB
  + PE
  + PI
  + PR
  + RJ
  + RN
  + RO
  + RR
  + RS
  + SC
  + SE
  + SP
  + TO
}

enum TipoPessoa {
  + FISICA
  + JURIDICA
}

enum Perfil {
  + GERENCIADOR_PESSOAS
  + GERENCIADOR_DOACOES
  + GERENCIADOR_CAPACITACOES
  + GERENCIADOR_ACESSO
  + GERENCIADOR_RELATORIOS
}

class Comorbidade {
  - id: Long
  - nome: String
  - descricao: String
  - dataInativo: LocalDateTime
}

class Categoria {
  - id: Long
  - nome: String
  - descricao: String
  - dataInativo: LocalDateTime
}

class Pessoa {
  - id: Long
  - nome: String
  - cpfCnpj: String
  - dataNascimento: LocalDate
  - telefone: String
  - email: String
  - profissao: String
  - descricao: String
  - dataInativo: LocalDateTime
  - cep: String
  - uf: Uf
  - cidade: String
  - bairro: String
  - logradouro: String
  - complementoEndereco: String
  - quantCoabitantes: Integer
  - tipoPessoa: TipoPessoa
  - ehDoador: Boolean
  - ehBeneficiario: Boolean
}

class Conta {
  - id: Long
  - pessoa: Pessoa
  - nomeUsuario: String
  - senhaHash: String
  - dataCriacao: LocalDateTime
  - dataInativo: LocalDateTime
  - perfis: Set<Perfil>
}

' Relacionamentos - Módulo de Pessoas
Pessoa "*" --> "0..1" Sexo : possui
Pessoa "*" --> "0..1" Escolaridade : possui
Pessoa "*" --> "0..1" RendaFamiliar : possui
Pessoa "*" --> "*" Categoria : possui
Pessoa "*" --> "*" Comorbidade : possui
Pessoa "*" --> "0..1" Uf : reside em
Pessoa "*" --> "1" TipoPessoa : e do tipo

' Relacionamentos - Módulo de Acesso
Conta "1" --> "1" Pessoa : vincula (pessoa_id)
Conta "1" *-- "*" Perfil : possui (contas_perfis)

@enduml