ALTER TABLE pessoa ADD COLUMN tipo_pessoa ENUM ('FISICA', 'JURIDICA') NOT NULL;
ALTER TABLE pessoa ADD COLUMN beneficiario BOOLEAN DEFAULT FALSE;

ALTER TABLE pessoa ADD COLUMN doador DATE DEFAULT NULL;

ALTER TABLE pessoa ADD COLUMN quantidade_coabitante TINYINT DEFAULT 0;

ALTER TABLE pessoa DROP cpf;

ALTER TABLE pessoa ADD COLUMN cpf_cnpj VARCHAR(14) NOT NULL UNIQUE;
