name: Deploy Angular
on:
  push:
    branches:
      - dev
    paths:
      - 'web/**'
jobs:
  deploy-angular:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout do código
        uses: actions/checkout@v7

      - name: Configurar Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - name: Instalar dependências
        run: npm ci

      - name: Build do Angular
        run: npm run build -- --configuration production

      - name: Copiar arquivos para o Nginx
        run: |
          rm -rf /var/www/h-asmosul/*

          cp -r dist/web/browser/* /var/www/h-asmosul/

          chmod -R 755 /var/www/h-asmosul/

